Source Code SecureMySocial/sms-core/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :groups do
      collection do
        post "/rules", :action => :add_system_rule
        match "/cron", :action => :system_cron, via: [:get, :post]
      end
      member do
        get "/reports", :action => :reports
        get "/alerts", :action => :alerts

        get "/rules", :action => :rules
        post "/rules", :action => :save_rules

        post "/import", :action => :import

        get "/users", :action => :users
        post "/users", :action => :save_users

        get "/options", :action => :options
        patch "/options", :action => :save_options

        post "/sysrules", :action => :update_group_system_rules
        post "/subgroup", :action => :add_subgroup
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/profile" => "profile#index", :as => :profile
  get "/alerts" => "profile#alerts", :as => :user_alerts
  patch "/profile" => "profile#update"

  get "/login/:provider" => "home#login", :as => :login

  get "/join/:token" => "groups#add_user"
  get "/join" => "home#join"

  root to: 'home#index'
end

Source Code SecureMySocial/sms-core/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @page_title %></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description" content="<%= @page_description %>"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "ex/application", :media => "all" %>
    <link rel="stylesheet" href="https://bootswatch.com/spacelab/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body id="body">
    <section id="header">
      <% if current_group && current_group.header.present? %>
        <%= raw current_group.header %>
      <% elsif current_group && current_group.parent && current_group.parent.header.present? %>
        <%= raw current_group.parent.header %>
      <% else %>
        <header>
          <div class="width-container">
            <span id="logo">
              <a href="http://www.securemysocial.com/" title="SecureMySocial" rel="home">
                <img src="/images/logo.png" alt="SMS" height="100">
              </a>
            </span>
          </header>
        <% end %>
    </div>
  </section>

    <section id="layout-body" class="container-fluid">
      <section class="container" id="layout-flash">
        <% unless devise_controller || @hide_login %>
          <div class="clearfix">
            <ul id="nav-links" class="list-inline pull-right">
              <% if user_signed_in? %>
                <li><%= link_to_unless_current "<i class='fa fa-home'></i>&nbsp;Home".html_safe, root_url %></li>
                <li><%= link_to_unless_current "<i class='fa fa-flash'></i>&nbsp;My Alerts".html_safe, user_alerts_url %></li>
                <li><%= link_to_unless_current "<i class='fa fa-cog'></i>&nbsp;My Account".html_safe, profile_url %></li>
                <li><%= link_to "<i class='fa fa-sign-out'></i>&nbsp;Sign out".html_safe, destroy_user_session_path, :method => :delete %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div id="flash">
          <% if alert %>
            <div id="alert" class="alert alert-danger alert-dismissable">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <%= alert %>
            </div>
          <% end %>
          <% if notice %>
            <div id="notice" class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <%= notice %>
            </div>
          <% end %>
        </div>
      </section>
      <%= yield %>
    </section>

    <section id="layout-footer">
      <% if current_group && current_group.footer.present? %>
        <%= raw current_group.footer %>
      <% elsif current_group && current_group.parent && current_group.parent.footer.present? %>
        <%= raw current_group.parent.footer %>
      <% else %>
        <footer>
          <div id="copyright">
            <div class="width-container">
              <div id="copyrigh-text">©<%= Date.today.year %> SecureMySocial, L.L.C. All Rights Reserved.</div>
            </div>
            <div class="clearfix"></div>
          </div>
        </footer>
      <% end %>
    </section>

    <%= javascript_include_tag "ex/application"  %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%= javascript_include_tag "main/application"  %>
    <%= yield :scripts %>

  </body>
</html>