Source Code SecureMySocial/sms-core/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :groups do
      collection do
        post "/rules", :action => :add_system_rule
        match "/cron", :action => :system_cron, via: [:get, :post]
      end
      member do
        get "/reports", :action => :reports
        get "/alerts", :action => :alerts

        get "/rules", :action => :rules
        post "/rules", :action => :save_rules

        post "/import", :action => :import

        get "/users", :action => :users
        post "/users", :action => :save_users

        get "/options", :action => :options
        patch "/options", :action => :save_options

        post "/sysrules", :action => :update_group_system_rules
        post "/subgroup", :action => :add_subgroup
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/profile" => "profile#index", :as => :profile
  get "/alerts" => "profile#alerts", :as => :user_alerts
  patch "/profile" => "profile#update"

  get "/login/:provider" => "home#login", :as => :login

  get "/join/:token" => "groups#add_user"
  get "/join" => "home#join"

  root to: 'home#index'
end

Source Code SecureMySocial/sms-core/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      if current_user.system_admin?
        return redirect_to admin_groups_path
      end

      if (group = current_user.admin_groups.first)
        return redirect_to admin_group_path(group)
      end

      if (group = current_user.phishing_admin_groups.first)
        return redirect_to reports_admin_group_path(group)
      end

      if (group = current_user.fraud_admin_groups.first)
        return redirect_to reports_admin_group_path(group)
      end
    else
      return redirect_to new_user_session_path
    end

    redirect_to profile_path
  end

  def join
    redirect_to "/" unless session[:sms_valid_token].present?

    @email = session[:sms_email]

    @hide_login = true
  end

  def login
    redirect_to omniauth_authorize_path(:user, params[:provider].to_sym)
  end

end

Source Code SecureMySocial/sms-core/app/views/home/join.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Join <%= @account_name %></h1>
    <p>Please authorize SecureMySocial App below to read and access your Twitter and Facebook accounts.</p>
    <p>By authorizing your accounts below, you agree to <a href="/tos" target="_blank">SecureMySocial terms of services</a></p>
    <p class="text-center hidden">
      <a href="<%= omniauth_authorize_path(:user, :twitter) %>" class="btn btn-primary btn-lg">
        <i class="fa fa-twitter"></i>
        Authorize account on Twitter
      </a>
      <a href="<%= omniauth_authorize_path(:user, :facebook) %>" class="btn btn-primary btn-lg">
        <i class="fa fa-facebook"></i>
        Authorize account on Facebook
      </a>
    </p>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Choose Password</h3>
      </div>

      <div class="panel-body">
        <%= form_for(:user, :url => registration_path(:user), :html => {:class => "form-horizontal"} ) do |f| %>
          <div class="form-group hidden">
            <%= f.label :email, :class => "control-label col-md-4" %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-none">@</i></span>
                <%= f.email_field :email, :class => "form-control", :value => @email %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password, :class => "control-label col-md-4" %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                <%= f.password_field :password, :class => "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, "Confirm Password", :class => "control-label col-md-4" %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                <%= f.password_field :password_confirmation, :class => "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-8 pull-right">
              <%= f.submit "Join", :class => "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  </div>
</div>