Source Code SecureMySocial/sms-core/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :groups do
      collection do
        post "/rules", :action => :add_system_rule
        match "/cron", :action => :system_cron, via: [:get, :post]
      end
      member do
        get "/reports", :action => :reports
        get "/alerts", :action => :alerts

        get "/rules", :action => :rules
        post "/rules", :action => :save_rules

        post "/import", :action => :import

        get "/users", :action => :users
        post "/users", :action => :save_users

        get "/options", :action => :options
        patch "/options", :action => :save_options

        post "/sysrules", :action => :update_group_system_rules
        post "/subgroup", :action => :add_subgroup
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/profile" => "profile#index", :as => :profile
  get "/alerts" => "profile#alerts", :as => :user_alerts
  patch "/profile" => "profile#update"

  get "/login/:provider" => "home#login", :as => :login

  get "/join/:token" => "groups#add_user"
  get "/join" => "home#join"

  root to: 'home#index'
end

Source Code SecureMySocial/sms-core/app/models/group.rb
class Group < ActiveRecord::Base

  has_many :members
  has_many :users, -> { distinct }, through: :members
  has_many :admin_members, -> { where(role: 'admin') }, class_name: 'Member'
  has_many :admin_users, -> { distinct }, through: :admin_members, source: :user
  has_many :regular_members, -> { where(role: 'user') }, class_name: 'Member'
  has_many :regular_users, -> { distinct }, through: :regular_members, source: :user
  has_many :fraud_members, -> { where(role: 'fraud_manager') }, class_name: 'Member'
  has_many :fraud_managers, -> { distinct }, through: :fraud_members, source: :user
  has_many :phishing_members, -> { where(role: 'phishing_manager') }, class_name: 'Member'
  has_many :phishing_managers, -> { distinct }, through: :phishing_members, source: :user

  has_many :rules
  has_many :system_rules, -> { where("deleted_at is null and rule_type in ('system', 'personal', 'career', 'financial') and source_rule_id is not null") }, class_name: 'Rule'

  belongs_to :parent, foreign_key: 'parent_group_id', class_name: 'Group'
  has_many :sub_groups, foreign_key: 'parent_group_id', class_name: 'Group'
  has_many :imports

  validates :name, presence: true

  scope :top_level, -> { where(parent_group_id: nil) }
  scope :with_counts, -> { select("groups.*,
                                   (select count(id) from members where group_id = groups.id and role = 'admin') as admins_count,
                                   (select count(id) from members where group_id = groups.id and role = 'user') as users_count") }

  has_many :alerts

  def top_level?
    parent_group_id.nil?
  end

  def description
    (top_level? ? "Account: " : "Group: ") + name
  end

  def maxed?(to_add=1)
    max = top_level? ? max_users : parent.max_users
    return false unless max
    gid = top_level? ? id : parent.id
    group_ids = Group.where(["id = :gid or parent_group_id = :gid", gid: gid]).pluck(:id)
    Member.where(group_id: group_ids).count + to_add > max
  end

end

Source Code SecureMySocial/sms-core/app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:index, :create, :update, :add_system_rule, :system_cron]
  before_action :set_admin_group, only: [:reports, :alerts]

  def index
    @top_level_groups = Group.top_level.with_counts.order(created_at: :desc)
    @system_rules = Rule.system.global.order(created_at: :desc)
    @personal_rules = Rule.personal.global.order(created_at: :desc)
    @career_rules = Rule.career.global.order(created_at: :desc)
    @financial_rules = Rule.financial.global.order(created_at: :desc)
    @business_rules = Rule.business.global.order(created_at: :desc)

    @builtin_rules = { system: @system_rules, career: @career_rules, personal: @personal_rules, financial: @financial_rules }
  end

  def show
    @group = current_user.admin_groups.find(params[:id])
    @sub_groups = @group.sub_groups

    @past_24h_alerts = @group.alerts.past_24h.count
    @past_24h_class = @past_24h_alerts > 0 ? "danger" : "success"
    @total_users = @group.regular_users.count
    @total_alerts = @group.alerts.count
    @total_facebook_accounts = @group.regular_users.facebook.count
    @total_twitter_accounts = @group.regular_users.twitter.count
  end

  def users
    @group = current_user.admin_groups.find(params[:id])
    @users = {}
    if @group.phishing
      @users['phishing_manager'] = @group.phishing_managers.order(created_at: :desc)
    end
    if @group.fraud
      @users['fraud_manager'] = @group.fraud_managers.order(created_at: :desc)
    end
    @users['user'] = @group.regular_users.order(created_at: :desc)
    @users['admin'] = @group.admin_users.order(created_at: :desc)
    @invited_members = Member.pending.where(group_id: @group.id).order(created_at: :desc)
  end

  def save_users
    @group = current_user.admin_groups.find(params[:id])
    if @group.maxed?
      return redirect_to(users_admin_group_path(@group.id), alert: "No more users can be added to this account")
    end
    member = Member.new(wcu(group_member_params).merge(role: params[:role]))
    @group.members << member
    if @group.save
      UserMailer.invite_user_to_group(member, @group).deliver_later
      flash[:notice] = "#{params[:role].capitalize} account was added successfully"
      redirect_to users_admin_group_path(@group, anchor: params[:role])
    else
      @admin_users = @regular_users = @invited_admins = @invited_users = []
      render :users
    end
  end

  def import
    @group = current_user.admin_groups.find(params[:id])
    @import = @group.imports.build(import_params.merge(user_id: current_user.id))
    if @import.has_valid_content? && @import.save
      flash[:notice] = "Import was saved and queued for processing"
    else
      flash[:alert] = "Could not sove this import"
    end
    redirect_to users_admin_group_path(@group, anchor: 'import')
  end

  def rules
    @group = current_user.admin_groups.find(params[:id])
    @business_rules = @group.rules.business.order(created_at: :desc)

    business_rules_sources = @business_rules.pluck(:source_rule_id)
    Rule.business.global.each do |rule|
      unless business_rules_sources.include?(rule.id)
        options = rule.slice(:name, :message, :description, :patterns, :rule_type, :quarantine,
                             :send_author, :send_admins, :include_post_content, :include_restore_link,
                             :phishing, :send_phishing_admins, :fraud, :send_fraud_admins)
        @group.rules << Rule.create(options.merge group_id: @group.id, source_rule_id: rule.id)
      end
    end

    @custom_rules = @group.rules.custom.non_system.order(created_at: :desc)
    @exception_rules = @group.rules.exception.non_system.order(created_at: :desc)
    @system_rules = Rule.system.global.with_selection_for_group(@group.id).order(created_at: :desc)
  end

  def reports
  end

  def alerts
    alerts = Alert.where(group_id: @group.id).joins(:rule).select("alerts.*, rules.name").order(created_at: :desc)
    if @role == 'phishing_manager'
      alerts = alerts.where(phishing: true)
    end
    if @role == 'fraud_manager'
      alerts = alerts.where(fraud: true)
    end
    alerts = alerts.map do |ar|
      {
        accountInfo: "#{ar.screen_name.present? ? 'Twitter' : 'Facebook'}: #{ar.screen_name.presence || ar.provider_from_name}",
        accountEmail: ar.author_email,
        accountPhone: ar.author_phone,
        postWrittenAt: ar.message_time.to_s(:db),
        ruleName: ar.name,
        postMessage: ar.message,
        phishingRelated: ar.phishing ? "Yes" : "",
        fraudRelated: ar.fraud ? "Yes" : "",
        postDeletedAt: ar.post_deleted_at.presence && ar.post_deleted_at.to_s(:time)
      }
    end

    render json: alerts
  end

  def save_rules
    @group = current_user.admin_groups.find(params[:id])
    params[:rule][:quarantine] = false unless params[:rule][:quarantine].present?
    params[:rule][:send_author] = false unless params[:rule][:send_author].present?
    params[:rule][:send_admins] = false unless params[:rule][:send_admins].present?
    params[:rule][:phishing] = false unless params[:rule][:phishing].present?
    params[:rule][:send_phishing_admins] = false unless params[:rule][:send_phishing_admins].present?
    params[:rule][:fraud] = false unless params[:rule][:fraud].present?
    params[:rule][:send_fraud_admins] = false unless params[:rule][:send_fraud_admins].present?
    params[:rule][:include_post_content] = false unless params[:rule][:include_post_content].present?
    params[:rule][:include_restore_link] = false unless params[:rule][:include_restore_link].present?
    if params[:rule] && params[:rule][:id]
      rule = @group.rules.active.find(params[:rule][:id])
      raise "invalid request" unless rule
      rule.attributes = rule_params
      rule.save!
    else
      rule = Rule.new(wcu(rule_params))
      @group.rules << rule
    end
    if @group.save
      flash[:notice] = "Rule was updated successfully"
      redirect_to rules_admin_group_path(@group, anchor: rule.anchor)
    else
      @rules = @system_rules = @business_rules = []
      render :show
    end
  end

  def add_system_rule
    params[:rule][:quarantine] = false unless params[:rule][:quarantine].present?
    params[:rule][:send_author] = false unless params[:rule][:send_author].present?
    params[:rule][:send_admins] = false unless params[:rule][:send_admins].present?
    params[:rule][:phishing] = false unless params[:rule][:phishing].present?
    params[:rule][:send_phishing_admins] = false unless params[:rule][:send_phishing_admins].present?
    params[:rule][:fraud] = false unless params[:rule][:fraud].present?
    params[:rule][:send_fraud_admins] = false unless params[:rule][:send_fraud_admins].present?
    params[:rule][:include_post_content] = false unless params[:rule][:include_post_content].present?
    params[:rule][:include_restore_link] = false unless params[:rule][:include_restore_link].present?
    if params[:rule] && params[:rule][:id]
      rule = Rule.find(params[:rule][:id])
      rule.attributes = rule_params
      notice = "Rule was updated successfully"
    else
      rule = Rule.new(wcu(rule_params))
      notice = "Rule was added successfully"
    end
    if rule.save
      flash[:notice] = notice
      redirect_to admin_groups_path
    else
      @top_level_groups = @system_rules = @business_rules = []
      render :show
    end
  end

  def add_subgroup
    group = current_user.admin_groups.find(params[:id])
    new_group = Group.new(parent_group_id: group.id,
                          name: params[:group][:name],
                          phishing: group.phishing,
                          fraud: group.fraud)
    member = Member.new(wcu(user_id: current_user.id).merge(role: 'admin', joined_at: Time.now.utc))
    new_group.members << member
    if new_group.save!
      flash[:notice] = "Group was added successfully"
      redirect_to admin_group_path(new_group)
    end
  end

  def update_group_system_rules
    @group = current_user.admin_groups.find(params[:id])

    current_rules_ids = @group.system_rules.pluck(:source_rule_id)
    new_rules_ids = []
    if params[:sysrules].present?
      new_rules_ids = params[:sysrules].keys.map(&:to_i)
      on_rules = new_rules_ids - current_rules_ids
      Rule.find(on_rules).each do |rule|
        options = rule.slice(:name, :message, :description, :patterns, :rule_type, :quarantine,
                             :send_author, :send_admins, :include_post_content, :include_restore_link,
                             :phishing, :send_phishing_admins, :fraud, :send_fraud_admins)
        @group.system_rules << Rule.create(options.merge group_id: @group.id, source_rule_id: rule.id)
      end
    end
    off_rules = current_rules_ids - new_rules_ids
    if off_rules.present?
      @group.system_rules.where(source_rule_id: off_rules).soft_delete
    end
    redirect_to rules_admin_group_path(@group)
  end

  def create
    group = Group.new wcu(group_params)
    member = Member.new(wcu(group_admin_params).merge(role: "admin"))
    group.members << member
    if group.save
      UserMailer.invite_user_to_group(member, group).deliver_later
      flash[:notice] = "Business account was added successfully"
      redirect_to "/admin/groups"
    else
      @top_level_groups = @system_rules =  @business_rules =[]
      render :index
    end
  end

  def update
    group = Group.top_level.find(params[:id])
    group.attributes = group_params
    if group.save
      flash[:notice] = "Business account was updated successfully"
      redirect_to "/admin/groups"
    else
      @top_level_groups = @system_rules =  @business_rules =[]
      render :index
    end
  end

  def options
    @group = current_user.admin_groups.find(params[:id])
  end

  def save_options
    @group = current_user.admin_groups.find(params[:id])
    @group.attributes = group_params
    if @group.save

Source Code SecureMySocial/sms-core/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def add_user
    member_record = Member.where(token: params[:token]).first
    if member_record
      remember_the_token(member_record)
      sign_out :user
      redirect_to "/join"
    else
      redirect_to root_path
    end
  end

  private
  def remember_the_token(member_record)
    session[:sms_valid_token] = member_record.token
    session[:sms_role] = member_record.role
    session[:sms_email] = member_record.invite_email
  end

end

Source Code SecureMySocial/sms-core/app/views/admin/groups/_add_business_account.html.erb
<div class="panel panel-primary">
  <div class="panel-heading" role="tab" id="add-new-business-account">
    <h4 class="panel-title">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-add-new-business-account" aria-expanded="false" aria-controls="collapse-add-new-business-account">
        <i class="fa fa-plus"></i>
        Add New Business Account
      </a>
    </h4>
  </div>
  <div id="collapse-add-new-business-account" class="panel-collapse collapse" role="tabpanel" aria-labelledby="add-new-business-account">
    <div class="panel-body">
      <%= form_tag "", class: "form-horizontal" do %>
        <div class="form-group">
          <label class="col-sm-3 control-label">Account Name</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" name="group[name]" placeholder="Name of business or entity" required />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Max # Users</label>
          <div class="col-sm-8">
            <input type="number" class="form-control" name="group[max_users]" required />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Custom Domain</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" name="group[domain]" placeholder="www.example.com" />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Options</label>
          <div class="col-sm-8">
            <div class="checkbox">
              <label>
                <input type="hidden" name="group[phishing]" value="off" />
                <input type="checkbox" name="group[phishing]"> Enable Phishing Features
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="hidden" name="group[fraud]" value="off" />
                <input type="checkbox" name="group[fraud]"> Enable Fraud Features
              </label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Admin Email</label>
          <div class="col-sm-8">
            <input type="email" class="form-control" name="group_admin[invite_email]" placeholder="Email address for the first admin of this account" required>
            <p class="help-block">We send the invite for managing the account here</p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Admin Name</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" name="group_admin[invite_first_name]" placeholder="First Name" required>
          </div>
          <div class="col-sm-4">
            <input type="text" class="form-control" name="group_admin[invite_last_name]" placeholder="Last Name" required>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-8">
            <button type="submit" class="btn btn-primary">Create Account and Send Invite</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

Source Code SecureMySocial/sms-core/app/views/admin/groups/_add_new_business_rule.html.erb
<div class="panel panel-primary">
  <div class="panel-heading" role="tab" id="add-new-business-rule">
    <h4 class="panel-title">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-add-new-business-rule" aria-expanded="false" aria-controls="collapse-add-new-business-rule">
        <i class="fa fa-plus"></i>
        Add New Business Rule Template
      </a>
    </h4>
  </div>
  <div id="collapse-add-new-business-rule" class="panel-collapse collapse" role="tabpanel" aria-labelledby="add-new-rule">
    <div class="panel-body">
      <%= form_tag rules_admin_groups_path, class: "form-horizontal" do %>
        <input type="hidden" name="rule[rule_type]" value="business" />
        <input type="hidden" name="rule[message]" value="" />
        <input type="hidden" name="rule[patterns]" value="" />
        <input type="hidden" name="rule[quarantine]" value="" />
        <input type="hidden" name="rule[send_author]" value="" />
        <input type="hidden" name="rule[send_admins]" value="" />
        <input type="hidden" name="rule[phishing]" value="" />
        <input type="hidden" name="rule[send_phishing_admins]" value="" />
        <input type="hidden" name="rule[fraud]" value="" />
        <input type="hidden" name="rule[send_fraud_admins]" value="" />
        <input type="hidden" name="rule[include_post_content]" value="" />
        <input type="hidden" name="rule[include_restore_link]" value="" />
        <div class="form-group">
          <label class="col-sm-3 control-label">Rule Name</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" name="rule[name]" placeholder="A name for the rule" required>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Descriprion</label>
          <div class="col-sm-8">
            <textarea class="form-control" name="rule[description]" rows="3" required></textarea>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-8">
            <button type="submit" class="btn btn-primary">Create Rule Template</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

Source Code SecureMySocial/sms-core/app/views/admin/groups/_add_new_rule.html.erb
<div class="panel panel-primary">
  <div class="panel-heading" role="tab" id="add-new-rule-<%= type %>">
    <h4 class="panel-title">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-add-new-rule-<%= type %>" aria-expanded="false" aria-controls="collapse-add-new-rule-<%= type %>">
        <i class="fa fa-plus"></i>
        Add New Rule
      </a>
    </h4>
  </div>
  <div id="collapse-add-new-rule-<%= type %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="add-new-rule-<%= type %>">
    <div class="panel-body">
      <%= form_tag rules_admin_groups_path, class: "form-horizontal" do %>
        <input type="hidden" name="rule[rule_type]" value="<%= type %>" />
        <div class="form-group">
          <label class="col-sm-3 control-label">Rule Name</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" name="rule[name]" placeholder="A name for the rule" required>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Alert Message</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" name="rule[message]" placeholder="The rule's alert message" required>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Descriprion</label>
          <div class="col-sm-8">
            <textarea class="form-control" name="rule[description]" rows="3" required></textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Patterns</label>
          <div class="col-sm-8">
            <textarea class="form-control" name="rule[patterns]" rows="6" required></textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Alerts</label>
          <div class="col-sm-8">
            <div class="checkbox">
              <label>
                <input type="checkbox" name="rule[send_author]" checked> Alert the author of the post
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="rule[send_admins]"> Alert the admins of the group
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="rule[include_post_content]" checked> Include content of triggering posts in alerts
              </label>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">Auto-deletion</label>
          <div class="col-sm-8">
            <div class="checkbox">
              <label>
                <input type="checkbox" name="rule[quarantine]"> Auto delete triggering posts on Twitter
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="rule[include_restore_link]"> Include restore link in auto-delete notification
              </label>
            </div>
          </div>
        </div>

        <% if @group && @group.phishing %>
          <div class="form-group">
            <label class="col-sm-3 control-label">Anti-Phishing</label>
            <div class="col-sm-8">
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="rule[phishing]"> Log possible phishing risk
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="rule[send_phishing_admins]"> Notify anti-phishing manager
                </label>
              </div>
            </div>
          </div>
        <% end %>

        <% if @group && @group.fraud %>
          <div class="form-group">
            <label class="col-sm-3 control-label">Anti-Fraud</label>
            <div class="col-sm-8">
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="rule[fraud]"> Log possible fraud risk
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="rule[send_fraud_admins]"> Notify anti-fraud manager
                </label>
              </div>
            </div>
          </div>
        <% end %>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-8">
            <button type="submit" class="btn btn-primary">Create Rule</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

Source Code SecureMySocial/sms-core/app/views/admin/groups/_system_rules.html.erb
<%= form_tag sysrules_admin_group_path(@group.id), class: "form-horizontal" do %>
  <% @system_rules.each do |rule| %>
    <div class="system-rule">
      <div class="checkbox">
        <label>
          <input type="checkbox" class="ajax-save sysrule-checkbox"
                 data-group-id=<%= @group.id %> data-system-rule-id=<%= rule.id %>
                 name="sysrules[<%= rule.id %>" <% if rule.sr_rule_id %>checked="checked"<% end %>/>
          <span>
            <strong><%= rule.name %></strong>
            <% if rule.sr_rule_id %>
              &nbsp;
              <a href="#" class="edit-system-rule-icon"
                          data-rule-id="<%= rule.sr_rule_id %>"
                          data-rule-message="<%= rule.sr_message.presence %>"
                          data-rule-quarantine="<%= rule.sr_quarantine.presence %>"
                          data-rule-send-author="<%= rule.sr_send_author.presence %>"
                          data-rule-send-admins="<%= rule.sr_send_admins.presence %>"
                          data-rule-phishing="<%= rule.sr_phishing %>"
                          data-rule-send-phishing-admins="<%= rule.sr_send_phishing_admins %>"
                          data-rule-fraud="<%= rule.sr_fraud %>"
                          data-rule-send-fraud-admins="<%= rule.sr_send_fraud_admins %>"
                          data-rule-include-restore-link="<%= rule.sr_include_restore_link %>"
                          data-rule-include-post-content="<%= rule.sr_include_post_content.presence %>">
                          <i class="fa fa-edit"></i></a>
            <% end %>
            <div>
              <em><%= truncate(rule.description, length: 200) %></em>
            </div>
          </span>
        </label>
      </div>
    </div>
  <% end %>
<% end %>

Source Code SecureMySocial/sms-core/app/views/admin/groups/show.html.erb
<div class="container">

  <%= render 'group_header', location: 'Users' %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @group.top_level? ? "Main Group" : @group.name %></h3>
    </div>

    <div class="panel-body">
      <div class="row">

        <div class="col-sm-3 col-sm-offset-1">
          <div class="sms-section text-center">
            <div class="sms-btn-group" role="group">
              <div class="text-center">
                <a href="<%= users_admin_group_path(@group) %>" class="btn btn-primary btn-block">
                  <i class="fa fa-group"></i> Manage Users
                </a>
              </div>
              <div class="text-center">
                <a href="<%= rules_admin_group_path(@group) %>" class="btn btn-primary btn-block">
                  <i class="fa fa-gavel"></i> Manage Rules
                </a>
              </div>
              <div class="text-center">
                <a href="<%= reports_admin_group_path(@group) %>" class="btn btn-primary btn-block">
                  <i class="fa fa-flag"></i> View Reports
                </a>
              </div>
              <div class="text-center">
                <a href="<%= options_admin_group_path(@group) %>" class="btn btn-primary btn-block">
                  <i class="fa fa-cog"></i> Settings
                </a>
              </div>
            </div>
          </div>
        </div>

        <div id="dashboard" class="col-sm-6 col-sm-offset-1">
          <div class="list-group">
            <a href="<%= reports_admin_group_path(@group) %>" class="list-group-item p24 <%= @past_24h_class %>">
              <h3 class="pull-right"><i class="fa fa-bell"></i></h3>
              <h4 class="list-group-item-heading count"><%= @past_24h_alerts %></h4>
              <p class="list-group-item-text"><strong>Last 24 Hours Alerts</strong></p>
            </a>
          </div>
          <div href="<%= users_admin_group_path(@group) %>" class="list-group">
            <a class="list-group-item users">
              <h3 class="pull-right"> <i class="fa fa-user"></i> </h3>
              <h4 class="list-group-item-heading count"><%= @total_users %></h4>
              <p class="list-group-item-text">Total Users</p>
            </a>
            <a href="<%= reports_admin_group_path(@group) %>" class="list-group-item alerts">
              <h3 class="pull-right"> <i class="fa fa-bolt"></i> </h3>
              <h4 class="list-group-item-heading count"><%= @total_alerts %></h4>
              <p class="list-group-item-text">Total Alerts</p>
            </a>
            <div class="list-group-item facebook-like">
              <h3 class="pull-right"> <i class="fa fa-facebook-square"></i> </h3>
              <h4 class="list-group-item-heading count"><%= @total_facebook_accounts %></h4>
              <p class="list-group-item-text">Connected Facebook Accounts</p>
            </div>
            <div class="list-group-item twitter">
              <h3 class="pull-right"> <i class="fa fa-twitter-square"></i> </h3>
              <h4 class="list-group-item-heading count"><%= @total_twitter_accounts %></h4>
              <p class="list-group-item-text">Connected Twitter Accounts</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <% if @group.top_level? %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Sub Groups</h3>
      </div>

      <div class="panel-body">
        <div class="col-sm-6">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newGroupModal">
            <i class="fa fa-plus"></i>
            Add New Sub Group
          </button>
        </div>
        <div class="col-sm-6">
          <% if @sub_groups.present? %>
            <%= collection_select(:group, :id, @sub_groups, :id, :name, { include_blank: 'Select a sub group to switch to' }, { class: "form-control" }) %>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="col-sm-6">
      <a href="<%= admin_group_path(@group.parent_group_id) %>" class="btn btn-default">
        <i class="fa fa-arrow-left"></i>
        Back to Main Group
      </a>
    </div>
  <% end %>
</div>


<div class="modal fade" id="newGroupModal" tabindex="-1" role="dialog" aria-labelledby="newGroupModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create a New Group</h4>
      </div>
      <%= form_tag subgroup_admin_group_path(@group.id), class: "form-horizontal" do %>
        <div class="modal-body">
          <div class="form-group">
            <label class="col-sm-3 control-label">Group Name</label>
            <div class="col-sm-8">
              <input id="group-name" type="text" class="form-control" name="group[name]" placeholder="The name of the group" required />
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i>Close</button>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Create group</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>